[build-system]
requires = [
    "setuptools>=36.6",
    "packaging",
    "wheel",
    "cython>=0.29.20",
    "numpy","scipy"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-Werror --strict-config --strict-markers"
testpaths = [
    "tests",
]
