[build-system]
requires = [
    "setuptools>=36.6",
    "packaging",
    "wheel",
    "cython",
    "numpy",
    "cupy-cuda101",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-Werror --strict-config --strict-markers"
testpaths = [
    "tests",
]
